# Generated by Django 5.1.2 on 2024-10-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_JSON', models.JSONField(verbose_name='Данные апдейта')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время получения апдейта')),
            ],
        ),
    ]
